# Generated by Django 2.2.5 on 2019-09-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('summ_initial', models.IntegerField(db_column='Initial summ', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DayCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField(db_column='Change date')),
                ('summ', models.IntegerField(db_column='Summ', max_length=5)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='BodyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_date', models.DateField(db_column='History date')),
                ('body', models.IntegerField(db_column='Body', max_length=5)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Loan')),
            ],
        ),
    ]
