# Generated by Django 2.2.5 on 2019-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyhistory',
            name='history_date',
            field=models.DateField(db_column='History_date'),
        ),
        migrations.AlterField(
            model_name='daycharge',
            name='charge_date',
            field=models.DateField(db_column='Change_date'),
        ),
    ]
