# Generated by Django 2.2.5 on 2019-09-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190902_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycharge',
            name='charge_date',
            field=models.DateField(db_column='Charge_date'),
        ),
    ]
